import React from 'react';

function Terms() {
  return (
    <div style={styles.container}>
      {/* --- HEADER --- */}
      <section style={styles.section}>
        <h1 style={styles.heading}>Terms of Service</h1>
        <p style={styles.tagline}>LAST UPDATED: MARCH 2026</p>
        <p style={styles.paragraph}>
          By accessing <strong>Legal-Lens Pro</strong>, you agree to the following terms. 
          As an <strong>AI Legal Scanner</strong> platform, we prioritize transparency. 
          Please read these terms carefully before analyzing your documents.
        </p>
      </section>

      {/* --- SECTION 1: AI NATURE --- */}
      <section style={styles.section}>
        <h2 style={styles.subheading}>1. Informational AI Nature</h2>
        <p style={styles.paragraph}>
          Legal-Lens Pro uses <strong>Google Gemini 1.5 Flash AI</strong> to perform automated 
          contract analysis. The results, including "Red Flags" and "Risk Scores," are 
          generated by a machine learning model. This is <strong>NOT</strong> a substitute 
          for professional legal advice from a certified attorney.
        </p>
      </section>

      {/* --- SECTION 2: INDIAN LAW LIMITATIONS --- */}
      <section style={styles.section}>
        <h2 style={styles.subheading}>2. Indian Contract Act 1872</h2>
        <p style={styles.paragraph}>
          While the tool is optimized for the <strong>Indian Contract Act 1872</strong>, 
          legal interpretations can vary by state and specific court rulings. We do 
          not guarantee 100% accuracy in identifying all potential legal liabilities 
          or local <strong>Gujarat</strong> specific amendments.
        </p>
      </section>

      {/* --- SECTION 3: PRIVACY & DATA --- */}
      <section style={styles.section}>
        <h2 style={styles.subheading}>3. Data Privacy & Processing</h2>
        <p style={styles.paragraph}>
          Your documents are processed in real-time. We do not store your uploaded 
          files on our private servers. However, data is sent to the Gemini API for 
          processing. We strongly advise <strong>redacting sensitive personal info</strong> 
          (Aadhar numbers, bank details) before scanning.
        </p>
      </section>

      {/* --- SECTION 4: USER RESPONSIBILITY --- */}
      <section style={styles.section}>
        <h2 style={styles.subheading}>4. User Responsibility</h2>
        <p style={styles.paragraph}>
          You are solely responsible for any decisions made based on the AI analysis. 
          The developer (Pragadishwar) and Legal-Lens Pro shall not be held liable for 
          any legal, financial, or personal consequences resulting from the use of this tool.
        </p>
      </section>
      </div>
  );
}

// --- STYLING ENGINE ---
const styles = {
  container: {
    padding: "60px 20px",
    color: "#e0e0e0",
    maxWidth: "900px",
    margin: "0 auto",
    lineHeight: "1.7",
    fontFamily: "'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    backgroundColor: "transparent"
  },
  section: {
    marginBottom: "50px",
    padding: "20px",
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderRadius: "10px",
    borderLeft: "2px solid #333"
  },
  heading: {
    fontSize: "2.8rem",
    marginBottom: "10px",
    background: "linear-gradient(90deg, #4da6ff, #b3d9ff)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    fontWeight: "800"
  },
  tagline: {
    fontSize: "0.9rem",
    color: "#666",
    fontWeight: "bold",
    letterSpacing: "2px",
    marginBottom: "30px"
  },
  subheading: {
    fontSize: "1.6rem",
    marginTop: "30px",
    marginBottom: "15px",
    color: "#4da6ff"
  },
  paragraph: {
    fontSize: "1.05rem",
    marginBottom: "15px",
    color: "#bbb"
  }
};

export default Terms;